### ISSUE TITLE
Total Time Column

### ISSUE THREAD

**Issue by ambiso** [PQShield/nist-sigs-zoo#13]
Would it make sense to add a total latency column that, for a given Mbit/s and GHz, computes the total time required for:

1. compute signature
2. send (public key +) signature over the network
3. verify signature

?

Kind regards,
ambiso

**Comment by thomwiggers** [comment]
Adding network transmission latency is a recipe for fairly misleading results, due to how TCP works: if public key/signature pair is in the first messages, you run into systems like TCP slow start and TCP's congestion window scaling. So I'm not entirely sure that this is helpful...

**Comment by ambiso** [comment]
I agree that it's not a trivial problem and very use-case specific.
For TLS various studies exist [1,2,3], and the problem has already been discussed at length on the pqc-forum [4].

I do wonder if these benchmarks in [1,2] are even representative of a typical web-page load. The time to first (meaningful) paint might be affected less than than the time to first payload byte (assuming the payload is large enough for the connection speed to ramp up).

I'll close it for now because the I believe the complexities involved to make sure the results aren't misleading probably make it out of scope for the project.

[1]: https://eprint.iacr.org/2019/1447.pdf#page=12
[2]: https://eprint.iacr.org/2020/071.pdf
[3]: https://www.researchgate.net/profile/Dimitrios-Sikeridis/publication/346646724_Assessing_the_Overhead_of_Post-Quantum_Cryptography_in_TLS_13_and_SSH/links/5ff3915992851c13feeb38fc/Assessing-the-Overhead-of-Post-Quantum-Cryptography-in-TLS-13-and-SSH.pdf
[4]: https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/anE3sBUWZS0/m/t7S8X25GBgAJ
