### ISSUE TITLE
AIMer not appearing in comparison

### ISSUE THREAD

**Issue by ldr709** [PQShield/nist-sigs-zoo#3]
It looks like AIMer is currently being left of the comparison chart. The easiest way to see this is to disable all other schemes. The comparison is then empty instead of including the AIMer schemes. My best guess for problem is that the scheme is called AIMer in [schemes.csv](https://github.com/PQShield/nist-sigs-zoo/blob/main/data/schemes.csv), but it's called AIMER in [parametersets.csv](https://github.com/PQShield/nist-sigs-zoo/blob/main/data/parametersets.csv).

Thanks for making this cool tool!

**Comment by thomwiggers** [comment]
I just fixed this in 3159d740329c63e00e7f015e302f41d0c5b5afff
