### ISSUE TITLE
Category column in the second table

### ISSUE THREAD

**Issue by dstebila** [PQShield/nist-sigs-zoo#7]
It would be informative to have the category column in the second (Parameters) table.

**Comment by thomwiggers** [comment]
Horizontal space is complicated, because otherwise usability on smaller screens goes bust. I will see if I have time to create a 1-table-to-rule-them-all version of the web page, that will be more like a widescreen spreadsheet, though.

**Comment by dstebila** [comment]
Indeed. But the new widescreen one addresses my needs, thanks!
